"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, FlaskConical, GitPullRequest, ShieldCheck, Users } from "lucide-react";
import { consultationService, dataSharingService, labService, organizationService, patientService, referralService } from "@services/api";
import { useAuth } from "@context/AuthContext";

type Item = Record<string, unknown>;
type Snapshot = { patients: Item[]; members: Item[]; consultations: Item[]; labs: Item[]; referrals: Item[]; grants: Item[]; unavailable: string[] };
const initial: Snapshot = { patients: [], members: [], consultations: [], labs: [], referrals: [], grants: [], unavailable: [] };
const asItems = (value: unknown): Item[] => Array.isArray(value) ? value as Item[] : value && typeof value === "object" ? ["data", "items", "results"].flatMap((key) => Array.isArray((value as Record<string, unknown>)[key]) ? (value as Record<string, unknown>)[key] as Item[] : []) : [];
const status = (value: unknown) => String(value ?? "").toLowerCase();
const dateValue = (item: Item) => String(item.updated_at ?? item.created_at ?? item.accessed_at ?? "");

export default function LiveOperationalOverview({ refreshVersion = 0 }: { refreshVersion?: number }) {
  const { activeWorkspace } = useAuth(); const orgId = activeWorkspace?.id;
  const [snapshot, setSnapshot] = useState<Snapshot>(initial); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!orgId) return; let cancelled = false; const load = async () => { setLoading(true); const consultations = await Promise.allSettled(["Pending", "In Progress", "Completed", "Cancelled"].map((status_filter) => consultationService.listConsultations(orgId, { status_filter: status_filter as "Pending" | "In Progress" | "Completed" | "Cancelled" }))); const requests = await Promise.allSettled([patientService.getPatients(orgId), organizationService.getMembers(orgId), labService.listOrganizationLabTests(orgId), referralService.listReferrals(orgId), dataSharingService.listShareGrants(orgId)]); if (cancelled) return; const labels = ["patients", "staff", "lab tests", "patient transfers", "data grants"]; const unavailable = requests.flatMap((result, index) => result.status === "rejected" ? [labels[index]] : []); const allConsultations = consultations.flatMap((result) => result.status === "fulfilled" ? asItems(result.value) : []); const uniqueConsultations = Array.from(new Map(allConsultations.map((item) => [String(item.id), item])).values()); setSnapshot({ patients: requests[0].status === "fulfilled" ? asItems(requests[0].value) : [], members: requests[1].status === "fulfilled" ? asItems(requests[1].value) : [], labs: requests[2].status === "fulfilled" ? asItems(requests[2].value) : [], referrals: requests[3].status === "fulfilled" ? asItems(requests[3].value) : [], grants: requests[4].status === "fulfilled" ? asItems(requests[4].value) : [], consultations: uniqueConsultations, unavailable: consultations.some((result) => result.status === "rejected") ? [...unavailable, "consultations"] : unavailable }); setLoading(false); }; void load(); return () => { cancelled = true; }; }, [orgId, refreshVersion]);
  const metrics = useMemo(() => { const openConsultations = snapshot.consultations.filter((item) => ["pending", "in progress"].includes(status(item.status))).length; const completed = snapshot.consultations.filter((item) => status(item.status) === "completed").length; const transferCompleted = snapshot.referrals.filter((item) => status(item.status) === "completed").length; const activeGrants = snapshot.grants.filter((item) => status(item.status) === "active").length; const activeStaff = snapshot.members.filter((item) => !["pending", "revoked", "cancelled", "inactive"].includes(status(item.status))).length; return { openConsultations, completed, transferCompleted, activeGrants, activeStaff }; }, [snapshot]);
  const activities = useMemo(() => [...snapshot.referrals.map((item) => ({ title: `Patient transfer ${status(item.status) || "updated"}`, time: dateValue(item) })), ...snapshot.consultations.map((item) => ({ title: `Consultation ${status(item.status) || "updated"}`, time: dateValue(item) })), ...snapshot.labs.map((item) => ({ title: `Lab test ${status(item.status) || "updated"}`, time: dateValue(item) }))].filter((item) => item.time).sort((a, b) => b.time.localeCompare(a.time)).slice(0, 5), [snapshot]);
  const cards = [{ label: "Patients", value: snapshot.patients.length, icon: Activity }, { label: "Active staff", value: metrics.activeStaff, icon: Users }, { label: "Open consultations", value: metrics.openConsultations, icon: FlaskConical }, { label: "Patient transfers", value: snapshot.referrals.length, icon: GitPullRequest }, { label: "Active data grants", value: metrics.activeGrants, icon: ShieldCheck }];
  return <><section className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-medium text-emerald-600">Live operational overview</p><h2 className="text-lg font-semibold text-slate-900">Current organization activity</h2>{snapshot.unavailable.length > 0 && <p className="mt-2 text-xs text-amber-700">Some live data is unavailable: {snapshot.unavailable.join(", ")}.</p>}<div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(({ label, value, icon: Icon }) => <article key={label} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><Icon className="h-4 w-4 text-[#051466]" /><p className="mt-3 text-2xl font-semibold">{loading ? "—" : value}</p><p className="text-xs text-slate-500">{label}</p></article>)}</div></section><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-emerald-600">Care delivery</p><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Completed consultations</dt><dd className="font-medium">{loading ? "—" : metrics.completed}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Lab tests ordered</dt><dd className="font-medium">{loading ? "—" : snapshot.labs.length}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Completed transfers</dt><dd className="font-medium">{loading ? "—" : metrics.transferCompleted}</dd></div></dl></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-emerald-600">Recent activity</p><div className="mt-4 space-y-3">{loading ? <p className="text-sm text-slate-500">Loading activity…</p> : activities.length === 0 ? <p className="text-sm text-slate-500">No recent operational activity recorded.</p> : activities.map((item) => <div key={`${item.title}-${item.time}`} className="flex gap-2 text-sm"><span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-emerald-500" /><div><p>{item.title}</p><p className="text-xs text-slate-500">{new Date(item.time).toLocaleString()}</p></div></div>)}</div></section></div></>;
}
