import { IncomingRecord } from "./IncomingRecordTypes";

export const incomingRecords: IncomingRecord[] = [
  {
    id: "1",
    initials: "ME",
    patientName: "Michael Eze",
    gpid: "GP123456",
    priority: "Urgent",
    condition: "Heart failure, needs surgery urgently",
    fromHospital: "UCH, Ibadan",
    requestedAt: "Apr 10, 12:45pm",
    records: ["Complete Medical History"],
    fileSize: "1.8 MB",
    status: "Pending",
    age: 34,
    gender: "Male",
    bloodGroup: "O+",
    genotype: "AA",
  },
  {
    id: "2",
    initials: "ME",
    patientName: "Michael Eze",
    gpid: "GP123456",
    priority: "Urgent",
    condition: "Heart failure, needs surgery urgently",
    fromHospital: "UCH, Ibadan",
    requestedAt: "Apr 10, 12:45pm",
    records: ["Complete Medical History"],
    fileSize: "1.8 MB",
    status: "Pending",
    age: 34,
    gender: "Male",
    bloodGroup: "O+",
    genotype: "AA",
  },
  {
    id: "3",
    initials: "ME",
    patientName: "Michael Eze",
    gpid: "GP123456",
    priority: "Urgent",
    condition: "Heart failure, needs surgery urgently",
    fromHospital: "UCH, Ibadan",
    requestedAt: "Apr 10, 12:45pm",
    records: ["Complete Medical History"],
    fileSize: "1.8 MB",
    status: "Accepted",
    age: 34,
    gender: "Male",
    bloodGroup: "O+",
    genotype: "AA",
  },
  {
    id: "4",
    initials: "ME",
    patientName: "Michael Eze",
    gpid: "GP123456",
    priority: "Urgent",
    condition: "Heart failure, needs surgery urgently",
    fromHospital: "UCH, Ibadan",
    requestedAt: "Apr 10, 12:45pm",
    records: ["Complete Medical History"],
    fileSize: "1.8 MB",
    status: "Rejected",
    age: 34,
    gender: "Male",
    bloodGroup: "O+",
    genotype: "AA",
  },
];